stages:
  - deploy

include:
  - local: '/templates/deploy_tpl.yml'

deploy:
  stage: deploy
  image: docker:dind
  variables:
    SSH_URL: ${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}
    SSH_PRIVATE_KEY: ${DEPLOY_PRIVATE_KEY}
    SSH_PORT: ${DEPLOY_SSH_PORT}
    DEPLOY_DIR: /tmp/${CI_COMMIT_SHORT_SHA}/
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    PROJECT_NAME: AppKeyCloak
    PROJECT_DOMAIN: iam-${CI_COMMIT_REF_NAME}.it.scancity.ru
  extends:
    - .deploy_tpl
  only:
    - main
