stages:
  - deploy

include:
  - project: 'iac/appcicd'
    ref: main
    file: '/templates/deploy_keycloak_tpl.yml'

master:deploy:
  stage: deploy
  image: docker:dind
  variables:
    SSH_URL: ${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}
    SSH_PRIVATE_KEY: ${DEPLOY_PRIVATE_KEY}
    SSH_PORT: ${DEPLOY_SSH_PORT}
    DEPLOY_DIR: /tmp/${CI_COMMIT_SHORT_SHA}/
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    DB_PORT: 3366
    PROJECT_NAME: AppDB
    PROJECT_DOMAIN: iam-${CI_COMMIT_REF_NAME}.it.scancity.ru
    PMA_HOSTS: mysql-${CI_COMMIT_REF_NAME}_mariadb,mysql_mariadb,mysql-testing_mariadb
    PMA_ARBITRARY: 1
  extends:
    - .deploy_tpl
  when: manual
  only:
    - main
